<?php

namespace Invi5h\LaravelShopify\Support\Socialite;

use SocialiteProviders\Manager\Helpers\ConfigRetriever as BaseConfigRetriever;

class ConfigRetriever extends BaseConfigRetriever
{
    protected function getFromServices($key)
    {
        return parent::getFromServices($key); // TODO: Change the autogenerated stub
    }

    protected function getConfigFromServicesArray($providerName)
    {
        if ('shopify' === $providerName) {
            return $this->servicesArray = [
                    'subdomain' => config('laravelshopify.subdomain'),
                    'client_id' => config('laravelshopify.api_key'),
                    'client_secret' => config('laravelshopify.api_secret'),
                    'redirect' => '/callback',
            ];
        }

        return parent::getConfigFromServicesArray($providerName);
    }
}
